In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [2]:
X = np.array([[0,1],[0,1],[-1,2],[5,7],[-3,2],[9,9]])
n = X.shape[0]
knn = NearestNeighbors(algorithm='kd_tree').fit(X)
neighbors = knn.kneighbors(X, n_neighbors=3, return_distance=False)
x = np.arange(n)

In [3]:
neighbors

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [3, 5, 1],
       [4, 2, 1],
       [5, 3, 1]])

In [4]:
neighbors[:,1:]

array([[1, 2],
       [1, 2],
       [0, 1],
       [5, 1],
       [2, 1],
       [3, 1]])

In [5]:
mask = neighbors != x[:, np.newaxis]
self_found = np.sum(~mask, axis=1) == 1
mask[:, -1] &= self_found
neighbors[mask].reshape((n, -1))

array([[1, 2],
       [0, 2],
       [0, 1],
       [5, 1],
       [2, 1],
       [3, 1]])