In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [15]:
X = np.array([[0,1],[0,1],[-1,2],[5,7],[-3,2],[9,9]])
n = X.shape[0]
knn = NearestNeighbors(algorithm='kd_tree').fit(X)
nbrs = knn.kneighbors(X, n_neighbors=3, return_distance=False)
x = np.arange(n)

In [16]:
nbrs

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [3, 5, 1],
       [4, 2, 1],
       [5, 3, 1]])

In [17]:
mask = nbrs != x[:, np.newaxis]
self_found = np.sum(~mask, axis=1) == 1
mask[:, -1] &= self_found
nbrs[mask].reshape((n, -1))
# idx = np.argsort()

array([[1, 2],
       [0, 2],
       [0, 1],
       [5, 1],
       [2, 1],
       [3, 1]])

In [18]:
idx

array([[0, 1, 2],
       [1, 0, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])